name: docs-chat
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10.11
  - conda-forge::cudatoolkit=11.8.0
  - conda-forge::cudnn=8.8.0.121
  - pytorch::pytorch==2.0.0
  - pytorch::torchvision==0.15.0
  - pytorch::torchaudio==2.0.0
  - pytorch::pytorch-cuda=11.8
  - pip
  - pip:
      - -r requirements.txt
